### ISSUE TITLE
using u2net

### ISSUE THREAD

**Issue by Bookwald** [ShamHyper/BgRemoverLite#1]
How do I add an u2net model such as isnet-anime.onnx for example?

**Comment by ShamHyper** [comment]
Most likely, in my version of the program using rembg, it will be impossible to use another version of the u2net model. But you can read how to do it on the rembg page.
https://pypi.org/project/rembg/

I tried to add the possibility of choshing model, but I encountered an error when using different versions of onnx, so a fix for this problem is not expected yet.
